#pragma once
#include "CoreMinimal.h"
#include "EG01BattleArtsType.generated.h"

UENUM(BlueprintType)
enum class EG01BattleArtsType : uint8 {
    None,
    SwordSkill,
    GreatSwordSkill,
    ShortSwordSkill,
    SpearSkill,
    AxeSkill,
    ClubSkill,
    BowSkill,
    MartialSkill,
    ClawSkill,
    EnemySkill,
    Pyrology,
    Hydrology,
    Terrology,
    Aerology,
    Cosmology,
    Umbrology,
    PyroTerrology,
    PyroAerology,
    HydroTerrology,
    HydroAerology,
    CosmoPyrology,
    CosmoHydrology,
    CosmoTerrology,
    CosmoAerology,
    UmbroPyrology,
    UmbroHydrology,
    UmbroTerrology,
    UmbroAerology,
    Item,
    Num,
    SkillStart = SwordSkill,
    SkillEnd = ClawSkill,
    SkillNum = ClawSkill,
    SpellStart = Pyrology,
    SpellEnd = Umbrology,
    SpellNum = ClubSkill,
    CombineStart = PyroTerrology,
    CombineEnd = UmbroAerology,
    CombineNum = Hydrology,
    ItemStart = Item,
    ItemEnd = Item,
    ItemNum = SwordSkill,
};

