#pragma once
#include "CoreMinimal.h"
#include "EG01BattleVoiceTriggerType.generated.h"

UENUM(BlueprintType)
enum class EG01BattleVoiceTriggerType : uint8 {
    BattleStart,
    BattleStartSurprise,
    BattleStartBack,
    BattleStartBoss,
    BattleWin1,
    BattleWin2,
    BattleWin3,
    BattleWinEasy1,
    BattleWinEasy2,
    BattleWinEasy3,
    BattleWinHard1,
    BattleWinHard2,
    BattleWinHard3,
    BattleEscapeEmperor,
    BattleEscapeOther,
    PartyCommandBattleBasic,
    PartyCommandBattleSurprise,
    PartyCommandBattleBack,
    PartyCommandBattleBoss,
    PartyCommandAlert,
    PartyCommandLinkReady,
    PartyCommandOther,
    InspirationSkill,
    InspirationAvoidSkill,
    InspirationCounterSkill,
    InspirationFathom,
    LearnSpell,
    LearnAbility,
    ActionStance,
    ActionShoutLight,
    ActionShoutHeavy,
    ActionRecover,
    ActionSelfRecover,
    HitDefeat,
    HitWeak,
    HitResist,
    HitAvoid,
    ReactionAvoid,
    ReactionResist,
    ReactionDefense,
    ReactionRecover,
    ReactionSupport,
    ReactionFaint,
    ReactionDead,
    ReactionAilmentHit,
    ReactionAilmentAvoid,
    ReactionDamageHeavy,
    ReactionDamageLight,
    ReactionSelfRecover,
    ReactionSelfSupport,
    ReactionSelfFaint,
    LinkIntro,
    LinkFirstOrder,
    LinkMiddleOrder,
    LinkLastOrder,
    Num,
    Invalid = 255,
};

