#pragma once
#include "CoreMinimal.h"
#include "EG01MenuAnimationEnum.generated.h"

UENUM(BlueprintType)
enum class EG01MenuAnimationEnum : uint8 {
    MENUTOP_WAIT,
    MENUSTATUS_WAIT,
    MENUTECHNIQUE_WAIT,
    MENUEQUIPMENT_WAIT,
    SWORD_WAIT,
    GREATSWORD_WAIT,
    SHORTSWORD_WAIT,
    WXE_WAIT,
    CLUB_WAIT,
    SPEAR_WAIT,
    BOW_WAIT,
    KNUCKLE_WAIT,
    SHIELD_WAIT,
    MENUABILITY_WAIT,
    MENUFORMATION_WAIT,
    MENULIBRARYENEMY_WAIT,
    THRONEMENU,
    MUSICAPPRECIATION_WAIT,
    IMPERIALTEST_CHECK,
    IMPERIALTEST_FINISH,
    IMPERIALTEST_THINK,
    IMPERIALTEST_WRITE,
    PARTYFORMATION_WAIT,
    EMPERORCHOICE_WAIT,
    SELECTLASTEMPEROR_WAIT,
    SELECTLASTEMPEROR_SIGNATUREPOSE,
    CHRONOLOGY_POSE,
    BATTLESEALED_WAIT,
    NUM,
};

