#pragma once
#include "CoreMinimal.h"
#include "EG01InteractObjectIconType.generated.h"

UENUM(BlueprintType)
enum class EG01InteractObjectIconType : uint8 {
    None,
    Talk,
    Inn,
    Shop,
    Pub,
    Throne,
    SkillArtsDojo,
    FormationTrainingCenter,
    SpellArtsLaboratory,
    Blacksmith,
    Informer,
    PartyOrganization,
    LearnAbility,
    ImperialUniversity,
    Ship,
    TreasureOpen,
    TreasureDiscover,
    SavePoint,
    Heal,
    EscapePoint,
    MusicRoom,
    Bed,
    Npc,
    FriendNpc,
    Enemy,
    Warp,
    HeroMemory,
    Teacher,
    HeroMemoryGimmick,
    Ladder,
    AvalonGarden,
    UmbroLab,
    SomonShip,
    MirammerShip00_SVA,
    MirammerShip01_SVA,
    MirammerShip02_SVA,
    MirammerShip00_NLO,
    MirammerShip01_NLO,
    MirammerShip02_NLO,
    MobelmShip,
    NuonoShip,
    TobaShip,
    MilesShip,
    DouglasShip,
    ForferShip,
    MermaidShip,
    TsukijimaShip,
    BiharahShip,
    TereltebaShip,
    YuyangShip,
    MulierShip,
};

