#pragma once
#include "CoreMinimal.h"
#include "EDebugSystemId.generated.h"

UENUM(BlueprintType)
enum class EDebugSystemId : uint8 {
    DEBUG_SYSTEM_ID_NONE,
    DEBUG_SYSTEM_ID_MAINMENU,
    DEBUG_SYSTEM_ID_CONSOLE_COMMAND,
    DEBUG_SYSTEM_ID_LOGSYSTEM,
    DEBUG_SYSTEM_ID_QUEST,
    DEBUG_SYSTEM_ID_QUEST_PROGRESS,
    DEBUG_SYSTEM_ID_LEVEL_TRANSITION,
    DEBUG_SYSTEM_ID_COLLISION,
    DEBUG_SYSTEM_ID_FIELD,
    DEBUG_SYSTEM_ID_INVENTORY,
    DEBUG_SYSTEM_ID_TECHNICAL_LEVEL,
    DEBUG_SYSTEM_ID_CONDUCT,
    DEBUG_SYSTEM_ID_BATTLE,
    DEBUG_SYSTEM_ID_BGM,
    DEBUG_SYSTEM_ID_EXIT,
};

