#include "ConvertExcelToDataTableG01AddedPotentCategoryTableTableRowStruct.h"

FConvertExcelToDataTableG01AddedPotentCategoryTableTableRowStruct::FConvertExcelToDataTableG01AddedPotentCategoryTableTableRowStruct() {
}

