#include "ConvertExcelToDataTableG01AddedPotentUsageTableTableRowStruct.h"

FConvertExcelToDataTableG01AddedPotentUsageTableTableRowStruct::FConvertExcelToDataTableG01AddedPotentUsageTableTableRowStruct() {
}

