#include "ConvertExcelToDataTableG01AddedPotentBaseTableTableRowStruct.h"

FConvertExcelToDataTableG01AddedPotentBaseTableTableRowStruct::FConvertExcelToDataTableG01AddedPotentBaseTableTableRowStruct() {
}

