

[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=3FD6DE0B4D803D4D4C13F790D3CF6384
ProjectName="Romancing SaGa 2 RotS"
ProjectDisplayedTitle=NSLOCTEXT("[/Script/EngineSettings]", "B16022024E9BB86E2BB4FCBE7B6E36AB", "Romancing SaGa 2 RotS")
CopyrightNotice=(C) SQUARE ENIX
bAllowWindowResize=False
bAllowMaximize=False
bAllowMinimize=True

[/Script/Engine.AssetManagerSettings]
-PrimaryAssetTypesToScan=(PrimaryAssetType="Map",AssetBaseClass=/Script/Engine.World,bHasBlueprintClasses=False,bIsEditorOnly=True,Directories=((Path="/Game/Maps")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=Unknown))
-PrimaryAssetTypesToScan=(PrimaryAssetType="PrimaryAssetLabel",AssetBaseClass=/Script/Engine.PrimaryAssetLabel,bHasBlueprintClasses=False,bIsEditorOnly=True,Directories=((Path="/Game")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=Unknown))
+PrimaryAssetTypesToScan=(PrimaryAssetType="Map",AssetBaseClass=/Script/Engine.World,bHasBlueprintClasses=False,bIsEditorOnly=True,Directories=((Path="/Game/Maps")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=Unknown))
+PrimaryAssetTypesToScan=(PrimaryAssetType="PrimaryAssetLabel",AssetBaseClass=/Script/Engine.PrimaryAssetLabel,bHasBlueprintClasses=False,bIsEditorOnly=True,Directories=((Path="/Game")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=Unknown))
+PrimaryAssetTypesToScan=(PrimaryAssetType="Widget",AssetBaseClass=/Script/UMG.UserWidget,bHasBlueprintClasses=True,bIsEditorOnly=False,Directories=,SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=Unknown))
;+PrimaryAssetTypesToScan=(PrimaryAssetType="ExcludePrimaryAssetLabel",AssetBaseClass=/Script/GameBaseSystemEd.ExcludePrimaryAssetLabel,bHasBlueprintClasses=False,bIsEditorOnly=True,Directories=((Path="/Game")),SpecificAssets=,Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=Unknown))
bOnlyCookProductionAssets=False
bShouldManagerDetermineTypeAndName=False
bShouldGuessTypeAndNameInEditor=True
bShouldAcquireMissingChunksOnLoad=False
MetaDataTagsForAssetRegistry=()

[/Script/GameBaseSystemEd.GameBaseSystemEdGlobalSetting]
MPresetName=(MPresetName="RS2Re")
MGlobalSettingPresetTable=/GameBaseSystem/System/Global/Data/DT_GameBaseSystemGlobalSettingPresetTable.DT_GameBaseSystemGlobalSettingPresetTable
MSettingInfo=(MFlagIDTable=/Game/Main/Flag/Data/DT_AllFlagInfoTable.DT_AllFlagInfoTable,MQuestParamTable=/Game/Main/Quest/Data/DT_AllQuestParam.DT_AllQuestParam,MItemIDTable=/Game/Main/Item/DataTable/DT_ItemData.DT_ItemData,MCollisionObjectIDTable=/Game/Main/CollisionObject/Data/DT_EventCollisionObjectID.DT_EventCollisionObjectID,MLevelObjectTypeTable=/Game/Main/LevelObjectFinder/Data/DT_LevelObjectAccessInfo.DT_LevelObjectAccessInfo,MLevelObjectIDTable=/Game/Main/LevelObjectFinder/Data/DT_LevelObjectName.DT_LevelObjectName,MInteractColliderTagTable=/Game/Main/Interact/Data/DT_InteractColliderTagTable.DT_InteractColliderTagTable,MLevelIDTable=/Game/Main/LevelMove/Data/DT_LevelTransitionTable.DT_LevelTransitionTable,MEventMainCatTable=/Game/Main/Event/Data/CategoryTable/DT_EventMainCatTable.DT_EventMainCatTable,MEventSubCatTable=/Game/Main/Event/Data/CategoryTable/DT_EventSubCatTable.DT_EventSubCatTable,MEventSubGroupTable=/Game/Main/Event/Data/CategoryTable/DT_EventSubGroupTable.DT_EventSubGroupTable,MSeqCategoryTable=/Game/Main/Sequencer/Data/DT_SequencerCategoryTable.DT_SequencerCategoryTable,MSeqTypeTable=/Game/Main/Sequencer/Data/DT_SequencerTypeImportData.DT_SequencerTypeImportData,MEnvironmentSettingTable=/Game/GraphicSystem/Environment/Preset/DataTable/DT_EnvironmentSettingDataAssetTable.DT_EnvironmentSettingDataAssetTable,MEffectDataTable=None,MDropItemDataTable=/Game/Main/Item/DataTable/DT_DropItem.DT_DropItem,MVFXDataTable=/Game/Prop/Effect/VFX/DataTable/DT_VFXDataTbl.DT_VFXDataTbl)

[/Script/UnrealEd.ProjectPackagingSettings]
Build=IfProjectHasCode
BuildConfiguration=PPBC_Development
BuildTarget=
StagingDirectory=(Path="F:/")
FullRebuild=False
ForDistribution=False
IncludeDebugFiles=False
BlueprintNativizationMethod=Disabled
bIncludeNativizedAssetsInProjectGeneration=False
bExcludeMonolithicEngineHeadersInNativizedCode=False
UsePakFile=True
bUseIoStore=True
bMakeBinaryConfig=False
bGenerateChunks=True
bGenerateNoChunks=False
bChunkHardReferencesOnly=False
bForceOneChunkPerFile=False
MaxChunkSize=0
bBuildHttpChunkInstallData=False
HttpChunkInstallDataDirectory=(Path="")
bCompressed=True
PakFileCompressionFormats=Oodle
bForceUseProjectCompressionFormatIgnoreHardwareOverride=False
PakFileAdditionalCompressionOptions=-compressionblocksize=256KB
PakFileCompressionMethod=Kraken
PakFileCompressionLevel_DebugDevelopment=3
PakFileCompressionLevel_TestShipping=5
PakFileCompressionLevel_Distribution=7
HttpChunkInstallDataVersion=
IncludePrerequisites=True
IncludeAppLocalPrerequisites=False
bShareMaterialShaderCode=True
bDeterministicShaderCodeOrder=False
bSharedMaterialNativeLibraries=True
ApplocalPrerequisitesDirectory=(Path="")
IncludeCrashReporter=False
InternationalizationPreset=All
-CulturesToStage=en
+CulturesToStage=ja
+CulturesToStage=ja-JP
+CulturesToStage=en
+CulturesToStage=en-US
+CulturesToStage=de-DE
+CulturesToStage=fr-FR
+CulturesToStage=ko-KR
+CulturesToStage=nyn-UG
+CulturesToStage=zh-CN
+CulturesToStage=zh-TW
+CulturesToStage=es-ES
LocalizationTargetCatchAllChunkId=0
bCookAll=False
bCookMapsOnly=False
bSkipEditorContent=True
bSkipMovies=True
+NonUFSMovies=MV_Common_E0060_C01_60
+NonUFSMovies=MV_Common_E0060_C05_60
+NonUFSMovies=MV_Common_E0060_C07_60
+NonUFSMovies=MV_Common_E0060_C08_60
+NonUFSMovies=MV_Common_E0060_C10_60
+NonUFSMovies=MV_Common_E0060_C11_60
+NonUFSMovies=MV_Common_E0060_C12_60
+NonUFSMovies=MV_Common_E0060_C13_60
+NonUFSMovies=MV_Common_E0060_C14_60
+NonUFSMovies=MV_Common_E0060_C25_60
+NonUFSMovies=MV_Mq0030_E0010_C01_60
+NonUFSMovies=MV_Mq0080_E0060_C04_60
+NonUFSMovies=MV_Mq0080_E0060_C05_60
+NonUFSMovies=MV_Mq0140_E0010_C01_60
+NonUFSMovies=MV_Mq0220_T0030_C01_60
+NonUFSMovies=MV_Mq0600_E0081_C03_60
+NonUFSMovies=MV_Mq0720_E0020_C09_60
+NonUFSMovies=MV_Mq1200_E0031_C13_60
+NonUFSMovies=MV_Mq1210_T0011_C02_60
+NonUFSMovies=MV_Mq1210_T0011_C03_60
+NonUFSMovies=MV_Mq1400_E0030_C19_60
+NonUFSMovies=MV_Mq1400_E0030_C30_T1_60
+NonUFSMovies=MV_Mq1400_E0030_C30_T2_60
+NonUFSMovies=MV_Mq1400_E0030_C30_T3_60
+NonUFSMovies=MV_Mq1400_E0030_C30_T4_60
+NonUFSMovies=MV_Mq1400_E0030_C31_T1_60
+NonUFSMovies=MV_Mq1400_E0030_C31_T2_60
+NonUFSMovies=MV_Mq1400_E0030_C32_T1_60
+NonUFSMovies=MV_Mq1400_E0030_C32_T2_60
+NonUFSMovies=MV_Mq1400_E0030_C33_T1_60
+NonUFSMovies=MV_Mq1400_E0030_C33_T2_60
+NonUFSMovies=MV_Mq1400_E0030_C34_T1_60
+NonUFSMovies=MV_Mq1400_E0030_C34_T2_60
+NonUFSMovies=MV_Mq1400_E0030_C35_T1_60
+NonUFSMovies=MV_Mq1400_E0030_C35_T2_60
+NonUFSMovies=MV_Mq1400_E0030_C36_T1_60
+NonUFSMovies=MV_Mq1610_E0010_C05_60
+NonUFSMovies=MV_Mq1620_E0201_C13_2_60
+NonUFSMovies=MV_Mq1620_E0201_C13_60
+NonUFSMovies=MV_Mq1620_E0201_C14_60
+NonUFSMovies=MV_Mq1620_E0201_C16_60
+NonUFSMovies=MV_Mq1620_E0201_C18_F_60
+NonUFSMovies=MV_Mq1620_E0201_C18_M_60
+NonUFSMovies=MV_Mq2100_E0010_C01_60
+NonUFSMovies=MV_Mq2100_E0010_C02_60
+NonUFSMovies=MV_Pm0050_E0010_C10_60
+NonUFSMovies=MV_Pm0070_E0010_C09_60
+DirectoriesToNeverCook=(Path="/GameBaseSystem/Editor")
+DirectoriesToNeverCook=(Path="/GameBaseSystem/EditorUtility")
+DirectoriesToNeverCook=(Path="/Game/Developers")
+DirectoriesToNeverCook=(Path="/Game/Editor")
+DirectoriesToNeverCook=(Path="/Game/SandBox")
+DirectoriesToAlwaysStageAsUFS=(Path="Debug/MainGame/Setting")
+DirectoriesToAlwaysStageAsUFS=(Path="Main/ConvertExcelToDataTable")
+DirectoriesToAlwaysStageAsUFS=(Path="Movie/Resource")
+DirectoriesToAlwaysStageAsUFS=(Path="SaveIcon")

[/Script/GameBaseSystem.GameBaseSystemGameSetting]
RegionType=JP
LevelMoveSubsystemHelperClass=BlueprintGeneratedClass'/Game/System/SubsystemHelper/LevelMove/BP_LevelMoveSubsystemHelper.BP_LevelMoveSubsystemHelper_C'
PlatformSubsystemHelperClass=BlueprintGeneratedClass'/Game/System/SubsystemHelper/Platform/BP_PlatformSubsystemHelper.BP_PlatformSubsystemHelper_C'
KeyConfigSubsystemHelperClass=BlueprintGeneratedClass'/Game/System/SubsystemHelper/KeyConfig/BP_KeyConfigSubsystemHelper.BP_KeyConfigSubsystemHelper_C'
AchievementSubsystemHelperClass=BlueprintGeneratedClass'/Game/System/SubsystemHelper/Achievement/BP_AchievementSubsystemHelper.BP_AchievementSubsystemHelper_C'
ActivitySubsystemHelperClass=BlueprintGeneratedClass'/Game/System/SubsystemHelper/Activity/BP_ActivitySubsystemHelper.BP_ActivitySubsystemHelper_C'
MIsTrial=False
AppNotificationSubsystemHelperClass=BlueprintGeneratedClass'/Game/System/SubsystemHelper/AppNotification/BP_AppNotificationSubsystemHelper.BP_AppNotificationSubsystemHelper_C'
;VisualActorHelperClass=BlueprintGeneratedClass'/Game/System/Helper/VisualActor/BP_VisualActorHelper.BP_VisualActorHelper_C'
FlagSubsystemHelperClass=/Game/System/SubsystemHelper/Flag/BP_FlagSubsystemHelper.BP_FlagSubsystemHelper_C
QuestSubsystemHelperClass=/Game/System/SubsystemHelper/Quest/BP_QuestSubsystemHelper.BP_QuestSubsystemHelper_C
SaveDataSubsystemHelperClass=/Game/System/SubsystemHelper/SaveData/BP_SaveDataSubsystemHelper.BP_SaveDataSubsystemHelper_C

[Internationalization]
+LocalizationPaths=%GAMEDIR%Content/Localization/NewTarget
+LocalizationPaths=%GAMEDIR%Content/Localization/MainGame_Debug
+LocalizationPaths=%GAMEDIR%Content/Localization/GameBaseSystem_Debug
+LocalizationPaths=%GAMEDIR%Content/Localization/GameStart_Debug
+LocalizationPaths=%GAMEDIR%Content/Localization/GameText
+LocalizationPaths=%GAMEDIR%Content/Localization/GameText_Debug

[/Script/GameBaseSystem.G01DebugImGuiSetting]
SubWindowTable=/Game/Debug/MainGame/Data/TD_DebugCreateSubWindow.TD_DebugCreateSubWindow
TabTable=/Game/Debug/MainGame/Data/DT_DebugCreateTabPage.DT_DebugCreateTabPage

[/Script/GameBaseSystem.GameBaseSystemDebugGameSetting]
DebugShortcutDataTableSoft=None

[/Script/RS2re.RS2reGameSetting]
TutorialSubsystemHelperClass=BlueprintGeneratedClass'/Game/Main/Tutorial/Helper/BP_TutorialSubsystemHelper.BP_TutorialSubsystemHelper_C'
TextSubsystemHelperClass=BlueprintGeneratedClass'/Game/System/SubsystemHelper/Text/BP_TextSubsystemHelper.BP_TextSubsystemHelper_C'

[/Script/WidgetBaseSystem.WidgetBaseSystemGameSetting]
WidgetDataSubsystemHelperClass=BlueprintGeneratedClass'/WidgetBaseSystem/System/SubSystemHelper/Widget/BP_WidgetDataSubsystemHelper.BP_WidgetDataSubsystemHelper_C'

